package com.wangln.greendaotest.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 24): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 24;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        OrdersDao.createTable(db, ifNotExists);
        OrderWithProductDao.createTable(db, ifNotExists);
        ProductsDao.createTable(db, ifNotExists);
        FriendDao.createTable(db, ifNotExists);
        PeopleDao.createTable(db, ifNotExists);
        PersonDao.createTable(db, ifNotExists);
        ProductDao.createTable(db, ifNotExists);
        TestDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
        People1Dao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        OrdersDao.dropTable(db, ifExists);
        OrderWithProductDao.dropTable(db, ifExists);
        ProductsDao.dropTable(db, ifExists);
        FriendDao.dropTable(db, ifExists);
        PeopleDao.dropTable(db, ifExists);
        PersonDao.dropTable(db, ifExists);
        ProductDao.dropTable(db, ifExists);
        TestDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
        People1Dao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(OrdersDao.class);
        registerDaoClass(OrderWithProductDao.class);
        registerDaoClass(ProductsDao.class);
        registerDaoClass(FriendDao.class);
        registerDaoClass(PeopleDao.class);
        registerDaoClass(PersonDao.class);
        registerDaoClass(ProductDao.class);
        registerDaoClass(TestDao.class);
        registerDaoClass(UserDao.class);
        registerDaoClass(People1Dao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
